test/bridge/BridgeConfigV3.ts

I noticed when writing another test that the `.to.be.not.reverted` blocks that aren't awaited aren't actually checked (see: https://github.com/TrueFiEng/Waffle/issues/95#issuecomment-1036639670). This fixes that issue.

fix awaits when checking for reverts (TrueFiEng/Waffle#95)

---

contracts/bridge/RateLimiter.sol
docs/bridge/RateLimiter.md
test/bridge/limiter/RateLimitedBridgeAVAX.t.sol
test/bridge/limiter/RateLimiter.t.sol

Added a bunch of new view functions for `RateLimiter`, updated the tests to cover them.
```solidity
function getTransactionAt(uint256 index)
external
view
returns (
bytes32 key,
bytes memory payload,
uint32 storedAtMin
);
function getTransactionByKappa(bytes32 kappa)
external
view
returns (bytes memory payload, uint32 storedAtMin);
function getUnhandledKappas()
external
view
returns (bytes32[] memory kappas);
function unhandledKappasCount() external view returns (uint256 kappaCount);
```
Checklist

RateLimiter: new view functions + their test coverage

---

.vscode/settings.json

Since we're still using Hardhat, the default dir for dependencies should be `node_modules`. Foundry libs are configured via `remappings.txt` at the moment.

fix VSCode settings

---

contracts/messaging/ContextChainIdUpgradeable.sol
contracts/messaging/HarmonyMessageBusUpgradeable.sol
contracts/messaging/MessageBusSenderUpgradeable.sol
test/messaging/HarmonyMessageBusUpgradeable.t.sol

This PR allows an easy creation of `MessageBus` contract for a specific chain, failing to report `block.chainid` correctly. The implementation can be later upgraded to chain-agnostic version.

MessageBus: add custom block.chainid option

---

.github/workflows/test.yaml
scripts/foundry-fork.sh
test/bridge/klaytn/KlaytnSynapseBridge.t.sol
test/bridge/wrappers/swap/CantoSwapWrapper.t.sol
test/bridge/wrappers/swap/LegacyCantoSwapWrapper.t.sol

- Fork tests are adjusted to use `vm.createSelectFork()` instead of relying on RPC URL to be provided in `forge test` command.
- Foundry scripts are adjusted
- Amount of fuzz runs in base tests increased to 2000 (these are quick anyway).

Fix: fork tests

---

contracts/bridge/interfaces/ISwapQuoter.sol
contracts/bridge/libraries/BridgeStructs.sol
contracts/bridge/router/SwapCalculator.sol
contracts/bridge/router/SwapQuoter.sol
contracts/bridge/router/SynapseAdapter.sol
contracts/bridge/router/SynapseRouter.sol
test/bridge/router/SwapCalculator.t.sol
test/bridge/router/SwapQuoter.t.sol
test/bridge/router/SynapseRouterUnsupported.t.sol

`SwapQuoter.getAmountOut()` is reworked to include `actionMask`: bitmask specifying what kind of actions should be considered when looking for a pool connecting `tokenIn` and `tokenOut`.
This is required because bridge swaps work differently on origin and destination chains:
- On origin chain, any swap is available. One could even swap through an external Swap Adapter.
- On destination chain only swap using the bridge token's "liquidity pool" is available. The set of actions is also limited:
- For mintable tokens there's only `mint()` and `mintAndSwap()`
- For withdrawable tokens there's only `withdraw` and `withdrawAndRemove()`
This PR takes it all into account to ensure that `getOriginAmountOut` + `getDestinationAmountOut` always gets a valid pair of `SwapQuery` structs for later use in …

Bitmasks for valid swap "actions"

---

contracts/bridge/router/SynapseRouter.sol
contracts/bridge/utils/MulticallView.sol
test/bridge/utils/MulticallView.t.sol

Adds `multicallView()`: a function to aggregate view calls into one to save on RPC requests. Function being `view` makes it possible to use off-chain without using `.callStatic`

Feat: multicall view

---

contracts/bridge/router/SwapQuoter.sol
test/bridge/router/SwapQuoter.t.sol

`SwapQuoter` is updated to always populate `tokenOut` field in the struct returned by `getAmountOut()`. This subtle change enables following:
https://github.com/synapsecns/synapse-contracts/blob/7ece713039e26d2a27416ecde74eea8e8b9afad7/test/bridge/router/SynapseRouterSuite.t.sol#L396-L409
Before the change, `getOriginAmountOut()` would return an empty struct with `tokenOut = address(0)` for every bridge token that is not connected to `tokenIn` on origin chain.
After the change, it would still return an empty struct for these tokens, but with a correct `tokenOut` address. This address could be used to find an alternative path between `tokenIn` and a bridge token, using an off-chain Quoter in a combination with an alternative Swap Adapter to perform the swap.
In fact, as it is guaranteed …

Always populate tokenOut field

---

test/bridge/router/SynapseRouterEndToEndEdgeCases.t.sol
test/bridge/router/SynapseRouterEndToEndGMX.t.sol
test/bridge/router/SynapseRouterEndToEndJewel.t.sol
test/bridge/router/SynapseRouterEndToEndNETH.t.sol
test/bridge/router/SynapseRouterEndToEndNUSD.t.sol
test/bridge/router/SynapseRouterSuite.t.sol
test/bridge/router/SynapseRouterSwap.t.sol
test/bridge/router/SynapseRouterUnsupported.t.sol
test/bridge/router/mocks/AaveMock.t.sol
test/utils/Utilities06.sol

A bunch of end-to-end tests covering bridging of following tokens have been added:
- `nUSD` and its connected stablecoins
- `nETH`, `WETH`, native `ETH` and Avalanche's `aWETH`
- `JEWEL`, including DFK where it is a gas token
- `GMX`
Also, e945a2b2bac1f63507608a06f179eb61f5a558e7 fixed the incorrect "find best path" algorithm, used in the test suite. A test to ensure the quote matches the one obtained straightforward way was also added.

Router: end to end tests

---

contracts/bridge/router/SwapQuoter.sol
contracts/bridge/router/SynapseRouter.sol
test/bridge/router/SwapQuoter.t.sol
test/bridge/router/SynapseRouterSuite.t.sol
test/bridge/router/SynapseRouterSwap.t.sol
test/bridge/router/SynapseRouterUnsupported.t.sol
test/bridge/router/SynapseRouterViews.t.sol

A small PR to enable contract deployments from a factory. As the deployer won't be the `msg.sender`, an extra `owner` argument is required in the constructor.

Owner transfership in constructor

---

test/bridge/wrappers/swap/CantoSwapWrapper.t.sol
test/bridge/wrappers/swap/LegacyCantoSwapWrapper.t.sol

Canto fork tests are no longer pinned to any block.
It looks as if the public Canto node we're using for tests (slingshot) does not handle the archive calls well,
thus removing the pin should lead to `foundry-fork` workflow to flake at a considerably lower rate.

Remove block pinning in Canto tests

---

.gitmodules
test/bridge/router/SynapseRouterEndToEndEdgeCases.t.sol
test/bridge/router/SynapseRouterEndToEndGMX.t.sol
test/bridge/router/SynapseRouterEndToEndJewel.t.sol
test/bridge/router/SynapseRouterEndToEndNETH.t.sol
test/bridge/router/SynapseRouterEndToEndNUSD.t.sol
test/bridge/router/SynapseRouterExpectations.t.sol
test/bridge/router/SynapseRouterOrigin.t.sol
test/bridge/router/SynapseRouterSuite.t.sol

`vm.expectEmit()` is now used as it its supposed to be used in the latest Foundry .

Fix router tests (new foundry)

---

contracts/cctp/SynapseCCTP.sol
contracts/cctp/events/MessageTransmitterEvents.sol
contracts/cctp/events/SynapseCCTPEvents.sol
contracts/cctp/events/TokenMessengerEvents.sol
contracts/cctp/interfaces/IMessageTransmitter.sol
contracts/cctp/interfaces/ISynapseCCTP.sol
contracts/cctp/interfaces/ITokenMessenger.sol
package.json
script/sh/flatten.sh
test/cctp/harnesses/TypeCastsLibHarness.sol
test/cctp/libs/TypeCasts.t.sol

This PR adds a very rough draft for the future CCTP integration. The sender specifies Circle token to bridge, as well as the request for the action to take on the destination chain (either transfer the bridge Circle token to recipient, or add an optional swap into another token first).
The request is hashed with the origin and destination domains, as well as the nonce of the sent CCTP message. This is hash is later used on destination chain to ensure that the provided request matches the one from origin domain.
> Origin, destination domains and nonce ensure that every "request hash" is unique for every message sent through `SynapseCCTP` on all the chains.

Feat: first draft for CCTP

---

contracts/cctp/SynapseCCTP.sol
contracts/cctp/events/SynapseCCTPEvents.sol
contracts/cctp/interfaces/IMessageTransmitter.sol
contracts/cctp/interfaces/IMintBurnToken.sol
contracts/cctp/interfaces/ISynapseCCTP.sol
contracts/cctp/interfaces/ITokenMessenger.sol
contracts/cctp/interfaces/ITokenMinter.sol
contracts/cctp/libs/Errors.sol
test/cctp/BaseCCTP.t.sol
test/cctp/SynapseCCTP.t.sol
test/cctp/mocks/MockMessageTransmitter.sol
test/cctp/mocks/MockMintBurnToken.sol
test/cctp/mocks/MockTokenMessenger.sol
test/cctp/mocks/MockTokenMinter.sol

First MVP implementation to get the Go tests started (and potentially fork tests as well).
- Only "base requests" are implemented at the moment.
- For base requests `requestVersion == 0` and `swapParams = ""`
- Support for bridge+swap will be added in the next PRs
- Bridge fees will be also added in the next PRs.
- `forge flatten` as well as a collection of mocks is added for go generate tests.
The implementation takes advantage of the fact that it's possible to restrict the destination caller that would be able to execute the CCTP message. Create2-deployed address with salt based on the request hash, origin and destination domains, as well as origin nonce is used. More details could be found in #233 description.

Feat: first MVP for Synapse CCTP

---

contracts/cctp/SynapseCCTP.sol
contracts/cctp/interfaces/IDefaultPool.sol
test/cctp/BaseCCTP.t.sol
test/cctp/SynapseCCTP.t.sol
test/cctp/mocks/MockDefaultPool.sol
test/cctp/mocks/MockERC20.sol

This PR adds support for "Swap" CCTP bridge requests. The origin sender has to specify following parameters for executing a swap on the destination chain:
https://github.com/synapsecns/synapse-contracts/blob/6bf4b6a33ba7b41022a6f4df98e20ea5ad00e81a/contracts/cctp/libs/Request.sol#L18-L24
On the destination chain, `SynapseCCTP` will try to perform a swap using the parameters from the origin request. Should the swap fail, the minted Circle token will be transferred to the recipient instead.

Feat: CCTP swap requests

---

contracts/cctp/SynapseCCTP.sol
contracts/cctp/events/SynapseCCTPFeesEvents.sol
contracts/cctp/fees/SynapseCCTPFees.sol
contracts/cctp/libs/Errors.sol
contracts/cctp/libs/Structs.sol
contracts/cctp/libs/TypeCasts.sol
test/cctp/BaseCCTP.t.sol
test/cctp/SynapseCCTP.t.sol
test/cctp/fees/SynapseCCTPFees.t.sol

This PR allows to setup and configure the "relayer fees" in `SynapseCCTP` contract. The relayer fees have a following structure:
- A percentage fee is applied to the amount of bridged Circle tokens. This fee has a hard cap of `10 bps`.
- The resulting fee has is then compared to the minimal relayer fee, and increased to match it, if needed.
- The minimal fee **is different** for Base and Swap requests. This is done to ensure that "brdige" fee could be smaller than "bridge + swap" fee.
- The fee is then compared to the maximum fee, and decreased to match it, if needed.
Anyone could be a relayer, as the integrity of the provided request is secured by CCTP itself (more details could be found in #233 and #235). Any relayer has an option to set up an address that will collect their earned …

Feat: CCTP fee config

---

contracts/cctp/SynapseCCTP.sol
test/cctp/SynapseCCTP.t.sol

Adds the ability to pause sending tokens via Circle CCTP. The ability to relay pending transactions is not affected, so even in the paused state all the pending ones could be resolved.

Add pausable state for sending tokens via CCTP

---

contracts/router/DefaultRouter.sol
contracts/router/adapters/DefaultAdapter.sol
contracts/router/interfaces/IDefaultExtendedPool.sol
contracts/router/interfaces/IDefaultPool.sol
contracts/router/interfaces/IRouterAdapter.sol
contracts/router/interfaces/IWETH9.sol
contracts/router/libs/Errors.sol
contracts/router/libs/Structs.sol
contracts/router/libs/UniversalToken.sol
test/mocks/MockTokenWithFee.sol
test/router/BaseTest.t.sol
test/router/DefaultRouter.t.sol
test/router/adapters/DefaultAdapter.t.sol
test/router/harnesses/ActionLibHarness.sol
test/router/harnesses/FlakyAdapter.sol
test/router/harnesses/UniversalTokenLibHarness.sol
test/router/libs/ActionLib.t.sol
test/router/libs/UniversalTokenLib.t.sol
test/router/mocks/MockDefaultExtendedPool.sol
test/router/mocks/MockDefaultPool.sol
test/router/mocks/MockERC20.sol
test/router/mocks/MockRevertingRecipient.sol
test/router/mocks/MockWETH.sol

This PR introduces two base contracts that will be used for future Router contracts, such as `SynapseCCTPRouter` and `SynapseRouterV2`.
`DefaultAdapter` implements functionality of a "default" Router adapter. The adapters are used to perform an origin swap in the Router contract using following workflow:
- Prepare to perform an action
- If adapter needs to perform an action with the ERC20 token, this token is transferred into the adapter contract first (and `msg.value=0` is used).
- If adapter needs to perform an action with native gas, it is attached using non-zero `msg.value` for the following call.
- Perform the action:
- `IRouterAdapter.adapterSwap(recipient, tokenIn, amountIn, tokenOut, rawParams)` is called
- `recipient`: the address that will receive the final token.
- `tokenIn`: …

Feat: common base for Router contracts

---

contracts/router/interfaces/IDefaultExtendedPool.sol
contracts/router/interfaces/IDefaultPoolCalc.sol
contracts/router/quoter/DefaultPoolCalc.sol
test/router/mocks/MockDefaultExtendedPool.sol
test/router/quoter/DefaultPoolCalc.t.sol

Isolated from #249 for the sake of keeping the PRs smaller.
Adds `DefaultPoolCalc`, which exposes a single function for quoting the amount of LP tokens obtained after addining liquidity to the pool. This function is not exposed in the pool (contrary to quotes for removing liquidity). The use cases:
- `SynapseRouter` periphery will be using this to get `DAI/USDC/USDT -> nUSD` quotes on Mainnet.
- SDK/UI could use this to provide accurate quotes for adding liquidity on other chains.

Feat: `addLiquidity()` calculator for Default Pools

---

contracts/router/interfaces/ISwapQuoterV2.sol
contracts/router/quoter/SwapQuoterV2.sol
test/router/quoter/SwapQuoterV2.GetAmountOut.Minted.t.sol
test/router/quoter/SwapQuoterV2.GetAmountOut.Origin.t.sol
test/router/quoter/SwapQuoterV2.GetAmountOut.Withdrawn.t.sol

Adds `areConnectedTokens()` getter, which follows the `getAmountOut()` conventions. Could be used to check if a theoretical path between provided tokens exists:
- `getAmountOut(tokenIn, tokenOut, amount) > 0` ⇒ `areConnectedTokens(tokenIn, tokenOut) == true`
- Tokens being connected doesn't necessarily mean that quote will be non-zero, as the pool could be empty/paused.

New getters in `SwapQuoterV2`

---

contracts/router/LinkedPool.sol
contracts/router/tree/TokenTree.sol
test/router/LinkedPool.t.sol
test/router/LinkedPoolModule.t.sol

To simplify the LinkedPool management:
- **Fix:** error thrown by pool modules is now bubbled (only applies for "external liquidity" such as GMX) to get more clarity around what caused the revert.
- **Fix**: events are now emitted on managements actions (add pool, update pool module).
- Chore: introduced `checkIndex` modifier to increase readbility.
- Chore: replaced string error messages with contract-specific custom errors.
https://github.com/synapsecns/synapse-contracts/blob/86fe0ceaf781a33072139e334e15f376249af743/contracts/router/LinkedPool.sol#L86
vs
https://github.com/synapsecns/synapse-contracts/blob/720eb37327526f8209efd0989a816b724f7e7ea1/contracts/router/LinkedPool.sol#L83

Fix: events and errors in `LinkedPool`

---

contracts/router/LinkedPool.sol
test/bridge/router/parityBoth/QuoterV2WithLinkedPoolSetup.t.sol
test/bridge/router/parityLinkedPool/LinkedPoolSetup.t.sol
test/router/LinkedPool.t.sol
test/router/modules/pool/LinkedPoolIntegration.t.sol
test/router/modules/pool/curve/CurveV1ModuleArb.t.sol
test/router/modules/pool/dss/DssPsmModule.t.sol
test/router/modules/pool/gmx/GMXV1ModuleArb.t.sol
test/router/modules/pool/uniswap/UniswapV3ModuleArb.t.sol
test/router/modules/pool/velodrome/VelodromeV2ModuleOpt.t.sol
test/utils/PoolUtils08.sol

This fix allows to deploy `LinkedPool` contract with owner other than `msg.sender`. This enables future factory deployments of `LinkedPool` contracts.

Fix: transfer ownership in `LinkedPool` constructor

---

contracts/router/interfaces/uniswap/ISwapRouter02.sol
contracts/router/modules/pool/uniswap/UniswapV3SR02Module.sol
deployments/avalanche/UniswapV3SR02Module.json
script/configs/avalanche/UniswapV3SR02Module.dc.json
script/router/modules/pool/uniswap/DeployUniswapV3SR02Module.s.sol
test/router/modules/pool/LinkedPoolUniswapV3SR02ModuleAvaxUSDC.t.sol
test/router/modules/pool/uniswap/UniswapV3SR02ModuleAvax.t.sol

Adds a slightly modified version of `UniswapV3Module` tailored for Avalanche Uniswap Router deployment:
https://gov.uniswap.org/t/deploy-uniswap-v3-on-avalanche/20587/18
https://snowtrace.io/address/0xbb00FF08d01D300023C629E8fFfFcb65A5a578cE
Caused by difference between Avalanche deployment and the other ones:
Everywhere else:
https://github.com/Uniswap/v3-periphery/blob/b13f9d9d9868b98b765c4f1d8d7f486b00b22488/contracts/interfaces/ISwapRouter.sol#L10-L19
Avalanche:
https://github.com/Uniswap/swap-router-contracts/blob/c696aada49b33c8e764e6f0bd0a0a56bd8aa455f/contracts/interfaces/IV3SwapRouter.sol#L10-L18

Deploy: avax uniswap v3 module

---

contracts/router/modules/bridge/SynapseCCTPModule.sol
test/router/modules/bridge/DelegateCaller.sol
test/router/modules/bridge/SynapseCCTPModule.t.sol

Adds a Bridge Module for `SynapseCCTP` contract to be used with new `SynapseRouterV2` contract. 
- It is using `SynapseCCTP` to get the supported tokens configuration.
- Older deployment of `SynapseCCTPRouter` is ignored, and its logic is reimplemented in the module.
Leaving links for reference:
- https://github.com/synapsecns/synapse-contracts/blob/master/contracts/cctp/SynapseCCTP.sol
- https://github.com/synapsecns/synapse-contracts/blob/master/contracts/cctp/fees/SynapseCCTPFees.sol

Feat: bridge module for `SynapseCCTP`

---

script/create2/DeployCreate2Factory.s.sol

This small PR updates `forge-std` dependency used for scripting and testing, and resolves the error (`CREATE2_FACTORY` was declared both in the script and in newer `forge-std` base contracts).

Chore: update `forge-std` to 1.7.1
