synapsecns/synapse-contracts

contracts/bridge/SynapseBridge.sol

Some modifications for both v1 and v2 fucntions

SynapseBridge.sol reworks

---

deploy/060_deploy_UST.ts
deployments/cronos/UST.json
deployments/metis/UST.json

Adds cronos/metis deployments (merged from `non-evm-addresses` which was squashed then merged. See #88

Add Cronos/Metis Changes

---

contracts/amm/SwapFlashLoan.sol
contracts/amm/SwapUtils.sol
contracts/bridge/BonusChef.sol
contracts/bridge/HarmonySynapseBridge.sol
contracts/bridge/MiniChefV2.sol
contracts/bridge/MiniChefV21.sol
contracts/bridge/MoonriverSynapseBridge.sol
contracts/bridge/interfaces/IMiniChefV2.sol

Modify IMiniChefV2 enough that MiniChefV21 can implement it

Make MiniChefV21 implement IMiniChefV2

---

deploy/061_deploy_NEWO.ts
deployments/arbitrum/NEWO.json
deployments/avalanche/NEWO.json

Deploys NEWO tokens on Avalanche & Arbitrum using ERC20 Factory

Deploy arbitrum/avalanche NEWO

---

deploy/061_deploy_SDT.ts
deployments/avalanche/SDT.json
deployments/fantom/SDT.json
deployments/harmony/SDT.json

Deploys $SDT support
Fixes # (issue)

deploy SDT

---

deploy/amm/100_deploy_nUSDV2Pool.ts
deploy/amm/100_deploy_nUSDV3Pool.ts
deployments/aurora/nUSDPoolV2-LPToken.json

the ABI for the nUSDPoolV2-LPToken seemed to be incorrectly recorded.
- fixed deploy scripts
- manually replaced ABI for `deployments/aurora/nUSDPoolV2-LPToken.json` by copy-pasting `LPToken.json` ABI

record correct nUSDPool LPToken ABIs

---

contracts/messaging/MessageBusSender.sol
contracts/messaging/dfk/bridge/HeroBridge.sol
contracts/messaging/dfk/bridge/HeroBridgeUpgradeable.sol
contracts/messaging/framework/SynMessagingReceiverUpgradeable.sol
scripts/UpdateHeroBridgeMessageBus.ts
test/dfk/HeroBridgeTest.sol

* Creates SynMessagingReceiverUpgradeable
Fixes # (issue)

Adjusts HeroBridge to be initializable and upgradeable

---

contracts/messaging/MessageBus.sol
contracts/messaging/MessageBusReceiver.sol
contracts/messaging/MessageBusSender.sol
package-lock.json
test/messaging/MessageBus.t.sol

Add pausable message bus

---

contracts/messaging/HarmonyMessageBusUpgradeable.sol
test/messaging/HarmonyMessageBusUpgradeable.t.sol
test/utils/Utilities.sol

- Added test to check how `HarmonyMessageBusUpgradeable` implementation upgrade affects storage state.
- Simplified its implementation as well.

Upgradeability check tests

---

contracts/messaging/dfk/bridge/HeroBridgeUpgradeable.sol

DFK Hero Bridge - Upgrade to remove assisting auction check

---

contracts/messaging/dfk/bridge/HeroBridgeUpgradeable.sol

Reverts synapsecns/synapse-contracts#182

Revert "DFK Hero Bridge - Upgrade to remove assisting auction check"

---

deploy/061_deploy_agEUR.ts
deployments/arbitrum/agEUR.json
deployments/optimism/agEUR.json

agEUR Arbitrum and Optimism deployment

---

deploy/061_deploy_PLS.ts

remove SDK dependency

---

deploy/005_deploy_LINK.ts
deploy/klaytn/1001_KlaytnBridge.ts

- `npx run prettier` to get the contracts linted => lint check is passed
- KlaytnBridge script now exists if current chain is not Klaytn => hardhat tests are passing

Fix scripts

---

.github/workflows/lint.yaml
deploy/005_deploy_LINK.ts
deploy/klaytn/1001_KlaytnBridge.ts
package.json

The CI workflow is updated to check if there are any files that need to be linted. Lint test is supposed to be failing, as `master` currently has an unformatted deploy script: `005_deploy_LINK.ts`
Failing lint check and tests are fixed in #195

Check lint in CI

---

.github/workflows/test.yaml
test/bridge/klaytn/KlaytnSynapseBridge.t.sol

Should fix the ever failing fork tests on Klaytn.

Rotate Klaytn public RPC url

---

.github/workflows/coveralls.yaml

Fix Github Runner

---

deploy/061_deploy_PLS.ts
deploy/061_deploy_UNIDX.ts
deployments/arbitrum/UNIDX.json

This adds the deploy script for the Unidex token which currently lives on Ethereum here: 0x95b3497bbcccc46a8f45f5cf54b0878b39f8d96c
Fixes # (issue)

Adding Unidex Token (xAsset)

---

contracts/cctp/libs/Errors.sol
contracts/cctp/libs/Request.sol
test/cctp/harnesses/RequestLibHarness.sol
test/cctp/libs/Request.t.sol

Supersedes #231. Implements encoding and decoding of the Requests without relying on a custom library.

Feat: CCTP request encoding

---

contracts/cctp/SynapseCCTPRouter.sol
contracts/cctp/interfaces/ISynapseCCTPFees.sol
contracts/cctp/interfaces/ISynapseCCTPRouter.sol
contracts/cctp/interfaces/ITokenMinter.sol
contracts/cctp/libs/RouterErrors.sol
contracts/router/libs/Structs.sol
deployments/arbitrum/SynapseCCTPRouter.json
deployments/avalanche/SynapseCCTPRouter.json
deployments/mainnet/SynapseCCTPRouter.json
script/cctp/DeploySynapseCCTPRouter.s.sol
test/cctp/SynapseCCTPRouter.t.sol
test/cctp/mocks/MockTokenMinter.sol

Feat: cctp router

---

contracts/router/interfaces/velodrome/IVelodromeV2Pool.sol
contracts/router/interfaces/velodrome/IVelodromeV2Router.sol
contracts/router/modules/pool/velodrome/VelodromeV2Module.sol
test/router/modules/pool/LinkedPoolVelodromeV2ModuleOptUSDC.t.sol
test/router/modules/pool/velodrome/VelodromeV2ModuleOpt.t.sol

feat: Velodrome V2 pool module

---

contracts/router/interfaces/dss/IDssGemJoin.sol
contracts/router/interfaces/dss/IDssPsm.sol
contracts/router/modules/pool/dss/DssPsmModule.sol
test/router/modules/pool/LinkedPoolDssPsmModuleEthUSDC.t.sol
test/router/modules/pool/LinkedPoolIntegration.t.sol
test/router/modules/pool/dss/DssPsmModule.t.sol

feat: DSS PSM pool module

---

contracts/router/LinkedPool.sol
contracts/router/modules/pool/curve/CurveV1Module.sol
contracts/router/modules/pool/dss/DssPsmModule.sol
contracts/router/modules/pool/gmx/GMXV1Module.sol
contracts/router/modules/pool/uniswap/UniswapV3Module.sol
contracts/router/modules/pool/velodrome/VelodromeV2Module.sol

UniversalTokenLib for infinite approvals

---

contracts/router/interfaces/IBridgeModule.sol
contracts/router/interfaces/IRouterV2.sol

feat: Router v2 interfaces

---

contracts/router/interfaces/IBridgeModule.sol

feat: tokenToActionMask view in IBridgeModule

---

contracts/router/quoter/SwapQuoterV2.sol
test/router/quoter/SwapQuoterV2.Management.t.sol

- Added events for every management-related action.
- Added contract-specific errors.

Chore: enforcing best practices in `SwapQuoterV2`

---

deployments/harmony/MockSwap.json
script/bridge/wrappers/DeployMockSwap.s.sol

Deploys `MockSwap` contract on Harmony.

Deploy harmony mock swap

---

test/bridge/BridgeConfigV3Lens.t.sol
test/bridge/klaytn/KlaytnSynapseBridge.t.sol
test/router/quoter/DefaultPoolCalc.t.sol

Chore: Update env names for RPC URL in the fork tests

---

contracts/router/interfaces/traderjoe/ILBPair.sol
contracts/router/interfaces/traderjoe/ILBRouter.sol
contracts/router/modules/pool/traderjoe/TraderJoeModule.sol
contracts/router/modules/pool/traderjoe/TraderJoeV21Module.sol
test/router/modules/pool/LinkedPoolTraderJoeV21ModuleAvaxUSDC.t.sol
test/router/modules/pool/traderjoe/TraderJoeV21ModuleAvax.t.sol

feat: TraderJoeV21PoolModule

---

contracts/router/modules/pool/traderjoe/TraderJoeModule.sol

Fixes import error given change in loc of `OnlyDelegateCall.sol`

fix: OnlyDelegateCall import in Trader Joe module

---

deployments/arbitrum/TraderJoeV21Module.json
deployments/avalanche/TraderJoeV21Module.json
deployments/bsc/TraderJoeV21Module.json
script/configs/arbitrum/TraderJoeV21Module.dc.json
script/configs/avalanche/TraderJoeV21Module.dc.json
script/configs/bsc/TraderJoeV21Module.dc.json
script/router/modules/pool/traderjoe/DeployTraderJoeV21Module.s.sol

Deployments to Avalanche, Arbitrum, BNB for `TraderJoeV21Module.sol`

Deploy: TraderJoeV21Module

---

contracts/cctp/interfaces/ISynapseCCTPConfig.sol
contracts/router/interfaces/IOwnable.sol
contracts/router/interfaces/ISwapQuoterV2.sol
contracts/router/libs/Arrays.sol
test/router/harnesses/ArraysLibHarness.sol
test/router/libs/Arrays.t.sol
test/router/v2/SynapseRouterV2Integration.t.sol
test/router/v2/integration/SynapseRouterV2.BridgeUtils.t.sol
test/router/v2/integration/SynapseRouterV2.CCTPUtils.t.sol
test/router/v2/integration/SynapseRouterV2.Integration.Arbitrum.t.sol
test/router/v2/integration/SynapseRouterV2.Integration.t.sol
test/utils/IntegrationUtils.sol

Integration tests on a few chains for `SynapseRouterV2.sol`.

Test: SynapseRouterV2 Integration

---

contracts/router/SynapseRouterV2.sol
contracts/router/interfaces/IRouterV2.sol
test/router/v2/SynapseRouterV2.Inspection.t.sol
test/router/v2/integration/SynapseRouterV2.Integration.Arbitrum.t.sol

Fix: Remove arrays from router v2 inputs

---

deployments/blast/FastBridge.json
deployments/blast/FastBridgeRouter.json

Deploy: blast fb router
